In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'c:\\Users\\tungf\\Desktop\\Vs code 資料\\rehab-accessibility-tainan\\notebooks'

In [3]:
file_path = "../data/raw/population_age_tainan_2024_12.csv"

In [4]:
file_path

'../data/raw/population_age_tainan_2024_12.csv'

In [5]:
df = pd.read_csv(file_path)

In [6]:
df.head()

,區域別,性別,總計,合計0至4歲人數,歲人數,合計5至9歲人數,合計10至14歲人數,合計15至19歲人數,合計20至24歲人數,合計25至29歲人數,...,合計55至59歲人數,合計60至64歲人數,合計65至69歲人數,合計70至74歲人數,合計75至79歲人數,合計80至84歲人數,合計85至89歲人數,合計90至94歲人數,合計95至99歲人數,歲人數以上
0,臺南市,計,1858873,53734,99,76731,78298,77730,94329,116159,...,143306,147207,129690,100635,54835,39667,24554,10830,2574,100
1,臺南市,男,921802,28047,99,39779,40536,40370,49051,60710,...,69935,71737,63142,47821,24859,16552,9399,3866,905,100
2,臺南市,女,937071,25687,99,36952,37762,37360,45278,55449,...,73371,75470,66548,52814,29976,23115,15155,6964,1669,100
3,新營區,計,74741,1936,99,3250,3538,3352,4226,4772,...,5600,5964,5345,4293,2448,1782,1133,498,115,100
4,新營區,男,36642,1014,99,1716,1800,1747,2201,2468,...,2668,2868,2486,2031,1136,762,457,162,38,100

In [7]:
df.shape

(114, 25)

In [8]:
df.columns.tolist()

['區域別',
 '性別',
 '總計',
 '合計0至4歲人數',
 '歲人數',
 '合計5至9歲人數',
 '合計10至14歲人數',
 '合計15至19歲人數',
 '合計20至24歲人數',
 '合計25至29歲人數',
 '合計30至34歲人數',
 '合計35至39歲人數',
 '合計40至44歲人數',
 '合計45至49歲人數',
 '合計50至54歲人數',
 '合計55至59歲人數',
 '合計60至64歲人數',
 '合計65至69歲人數',
 '合計70至74歲人數',
 '合計75至79歲人數',
 '合計80至84歲人數',
 '合計85至89歲人數',
 '合計90至94歲人數',
 '合計95至99歲人數',
 '歲人數以上']

In [9]:
for i, col in enumerate(df.columns):
    print(i, repr(col))

0 '區域別'
1 '性別'
2 '總計'
3 '合計0至4歲人數'
4 '歲人數'
5 '合計5至9歲人數'
6 '合計10至14歲人數'
7 '合計15至19歲人數'
8 '合計20至24歲人數'
9 '合計25至29歲人數'
10 '合計30至34歲人數'
11 '合計35至39歲人數'
12 '合計40至44歲人數'
13 '合計45至49歲人數'
14 '合計50至54歲人數'
15 '合計55至59歲人數'
16 '合計60至64歲人數'
17 '合計65至69歲人數'
18 '合計70至74歲人數'
19 '合計75至79歲人數'
20 '合計80至84歲人數'
21 '合計85至89歲人數'
22 '合計90至94歲人數'
23 '合計95至99歲人數'
24 '歲人數以上'

In [10]:
with open(file_path, "r", encoding="utf-8-sig") as f:
    header = f.readline()

print(header)

區域別,性別,總計,合計0至4歲人數,歲人數,合計5至9歲人數,合計10至14歲人數,合計15至19歲人數,合計20至24歲人數,合計25至29歲人數,合計30至34歲人數,合計35至39歲人數,合計40至44歲人數,合計45至49歲人數,合計50至54歲人數,合計55至59歲人數,合計60至64歲人數,合計65至69歲人數,合計70至74歲人數,合計75至79歲人數,合計80至84歲人數,合計85至89歲人數,合計90至94歲人數,合計95至99歲人數,歲人數以上

In [11]:
age_group_cols = [
    "合計0至4歲人數",
    "合計5至9歲人數",
    "合計10至14歲人數",
    "合計15至19歲人數",
    "合計20至24歲人數",
    "合計25至29歲人數",
    "合計30至34歲人數",
    "合計35至39歲人數",
    "合計40至44歲人數",
    "合計45至49歲人數",
    "合計50至54歲人數",
    "合計55至59歲人數",
    "合計60至64歲人數",
    "合計65至69歲人數",
    "合計70至74歲人數",
    "合計75至79歲人數",
    "合計80至84歲人數",
    "合計85至89歲人數",
    "合計90至94歲人數",
    "合計95至99歲人數",
    "歲人數以上"
]

In [12]:
df_check = df[df["性別"] == "計"].copy()

(
    df_check[age_group_cols].sum(axis=1)
    == df_check["總計"]
).value_counts()

False    38
Name: count, dtype: int64

### Data Quality Note

The 2024 population CSV contains malformed columns named `歲人數` and
`歲人數以上`. Therefore, the 65+ population was not calculated by directly
summing the reported 65+ age columns.

Instead:

population aged 65+ = total population - population aged 0–64

The result was validated by comparing it with the sum of the 65–99 age
groups and checking the implied 100+ population.

In [13]:
df_check = df[df["性別"] == "計"].copy()

df_check["age_sum_check"] = df_check[age_group_cols].sum(axis=1)

df_check["gap"] = (
    df_check["總計"]
    - df_check["age_sum_check"]
)

df_check[
    ["區域別", "總計", "age_sum_check", "gap", "歲人數", "歲人數以上"]
].head(10)

    區域別       總計  age_sum_check  gap  歲人數  歲人數以上
0   臺南市  1858873        1858656  217   99    100
3   新營區    74741          74827  -86   99    100
6   鹽水區    23984          24078  -94   99    100
9   白河區    25434          25526  -92   99    100
12  柳營區    20032          20130  -98   99    100
15  後壁區    21346          21438  -92   99    100
18  東山區    18866          18961  -95   99    100
21  麻豆區    43053          43140  -87   99    100
24  下營區    22099          22194  -95   99    100
27  六甲區    21140          21238  -98   99    100

In [14]:
under_65_cols = [
    "合計0至4歲人數",
    "合計5至9歲人數",
    "合計10至14歲人數",
    "合計15至19歲人數",
    "合計20至24歲人數",
    "合計25至29歲人數",
    "合計30至34歲人數",
    "合計35至39歲人數",
    "合計40至44歲人數",
    "合計45至49歲人數",
    "合計50至54歲人數",
    "合計55至59歲人數",
    "合計60至64歲人數"
]

In [15]:
df_check = df[df["性別"] == "計"].copy()

df_check["population_under_65"] = (
    df_check[under_65_cols].sum(axis=1)
)

df_check["population_65_plus"] = (
    df_check["總計"]
    - df_check["population_under_65"]
)

In [16]:
df_check[
    ["區域別", "總計", "population_under_65", "population_65_plus"]
].head(10)

    區域別       總計  population_under_65  population_65_plus
0   臺南市  1858873              1495771              363102
3   新營區    74741                59113               15628
6   鹽水區    23984                18282                5702
9   白河區    25434                18121                7313
12  柳營區    20032                15098                4934
15  後壁區    21346                15108                6238
18  東山區    18866                13578                5288
21  麻豆區    43053                33256                9797
24  下營區    22099                16451                5648
27  六甲區    21140                16296                4844

In [17]:
age_65_to_99_cols = [
    "合計65至69歲人數",
    "合計70至74歲人數",
    "合計75至79歲人數",
    "合計80至84歲人數",
    "合計85至89歲人數",
    "合計90至94歲人數",
    "合計95至99歲人數"
]

df_check["population_65_to_99"] = (
    df_check[age_65_to_99_cols].sum(axis=1)
)

In [18]:
df_check["implied_100_plus"] = (
    df_check["population_65_plus"]
    - df_check["population_65_to_99"]
)

In [19]:
df_check[
    [
        "區域別",
        "population_65_plus",
        "population_65_to_99",
        "implied_100_plus"
    ]
].head(10)

    區域別  population_65_plus  population_65_to_99  implied_100_plus
0   臺南市              363102               362785               317
3   新營區               15628                15614                14
6   鹽水區                5702                 5696                 6
9   白河區                7313                 7305                 8
12  柳營區                4934                 4932                 2
15  後壁區                6238                 6230                 8
18  東山區                5288                 5283                 5
21  麻豆區                9797                 9784                13
24  下營區                5648                 5643                 5
27  六甲區                4844                 4842                 2

In [20]:
district_check = df_check[
    df_check["區域別"] != "臺南市"
].copy()

In [21]:
df_population_2024 = district_check[
    ["區域別", "總計", "population_65_plus"]
].copy()

df_population_2024.columns = [
    "district",
    "total_population",
    "population_65_plus"
]

In [22]:
df_population_2024["pct_65_plus"] = (
    df_population_2024["population_65_plus"]
    / df_population_2024["total_population"]
    * 100
)

In [23]:
print(df_population_2024.shape)
print(df_population_2024.isna().sum())
print(df_population_2024["district"].duplicated().sum())

(37, 4)
district              0
total_population      0
population_65_plus    0
pct_65_plus           0
dtype: int64
0

In [24]:
output_path = "../data/processed/population_tainan_2024_clean.csv"

df_population_2024.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

In [25]:
district_check = df_check[
    df_check["區域別"] != "臺南市"
].copy()

district_check["implied_100_plus"].sum()

np.int64(317)

In [26]:
age_65_plus_cols = [
    "合計65至69歲人數",
    "合計70至74歲人數",
    "合計75至79歲人數",
    "合計80至84歲人數",
    "合計85至89歲人數",
    "合計90至94歲人數",
    "合計95至99歲人數",
    "100歲人數以上"
]

[col for col in age_65_plus_cols if col not in df.columns]

['100歲人數以上']

In [27]:
df["性別"].value_counts()

性別
計    38
男    38
女    38
Name: count, dtype: int64

In [28]:
df_total = df[df["性別"] == "計"].copy()

In [29]:
df_total.shape

(38, 25)

In [30]:
df_district = df_total[df_total["區域別"] != "臺南市"].copy()

In [31]:
df_district.shape

(37, 25)

In [32]:
columns_to_keep = [
    "區域別",
    "總計",
    "合計65至69歲",
    "合計70至74歲",
    "合計75至79歲",
    "合計80至84歲",
    "合計85至89歲",
    "合計90至94歲",
    "合計95至99歲",
    "100歲以上"
]

In [33]:
columns_to_keep

['區域別',
 '總計',
 '合計65至69歲',
 '合計70至74歲',
 '合計75至79歲',
 '合計80至84歲',
 '合計85至89歲',
 '合計90至94歲',
 '合計95至99歲',
 '100歲以上']

In [34]:
age_65_plus_cols = [
    "合計65至69歲",
    "合計70至74歲",
    "合計75至79歲",
    "合計80至84歲",
    "合計85至89歲",
    "合計90至94歲",
    "合計95至99歲",
    "100歲以上"
]

In [35]:
age_65_plus_cols

['合計65至69歲',
 '合計70至74歲',
 '合計75至79歲',
 '合計80至84歲',
 '合計85至89歲',
 '合計90至94歲',
 '合計95至99歲',
 '100歲以上']