In [2]:
import pandas as pd

In [3]:
file_path = "../data/raw/pt_workforce_tainan_2024.xlsx"

In [4]:
df_raw = pd.read_excel(file_path, header=None)

In [5]:
df_raw.head(8)

           0    1       2         3
0  機構執業醫事人員數  NaN     NaN       NaN
1        項目別  NaN     NaN  物理治療師(人)
2       113年  臺南市     NaN       794
3        NaN  NaN  臺南市新營區        26
4        NaN  NaN  臺南市鹽水區         0
5        NaN  NaN  臺南市白河區         3
6        NaN  NaN  臺南市柳營區        26
7        NaN  NaN  臺南市後壁區         2

In [6]:
df_raw.shape

(40, 4)

In [7]:
df_raw.tail(8)

      0    1       2    3
32  NaN  NaN  臺南市龍崎區    0
33  NaN  NaN  臺南市永康區  115
34  NaN  NaN   臺南市東區  124
35  NaN  NaN   臺南市南區   46
36  NaN  NaN   臺南市北區  117
37  NaN  NaN  臺南市安南區   75
38  NaN  NaN  臺南市安平區   21
39  NaN  NaN  臺南市中西區   79

In [8]:
df_pt = df_raw.iloc[3:, [2, 3]].copy()

In [9]:
df_pt.shape

(37, 2)

In [10]:
df_pt.head()

        2   3
3  臺南市新營區  26
4  臺南市鹽水區   0
5  臺南市白河區   3
6  臺南市柳營區  26
7  臺南市後壁區   2

In [11]:
df_pt.columns = ["district", "pt_count"]

In [12]:
df_pt.head()

  district pt_count
3   臺南市新營區       26
4   臺南市鹽水區        0
5   臺南市白河區        3
6   臺南市柳營區       26
7   臺南市後壁區        2

In [13]:
df_pt["district"] = df_pt["district"].str.removeprefix("臺南市")

In [14]:
df_pt.head()

  district pt_count
3      新營區       26
4      鹽水區        0
5      白河區        3
6      柳營區       26
7      後壁區        2

In [15]:
df_pt["pt_count"].sum()

794

In [16]:
df_pt.dtypes

district       str
pt_count    object
dtype: object

In [17]:
df_pt["pt_count"].apply(type).value_counts()

pt_count
<class 'int'>    37
Name: count, dtype: int64

In [18]:
df_pt["pt_count"] = pd.to_numeric(df_pt["pt_count"])

In [19]:
df_pt.dtypes

district      str
pt_count    int64
dtype: object

In [20]:
(df_pt["pt_count"] == 0).sum()

np.int64(16)

In [21]:
df_pt[df_pt["pt_count"] == 0]

   district  pt_count
4       鹽水區         0
8       東山區         0
10      下營區         0
11      六甲區         0
12      官田區         0
13      大內區         0
16      西港區         0
18      將軍區         0
19      北門區         0
23      安定區         0
24      山上區         0
25      玉井區         0
26      楠西區         0
27      南化區         0
28      左鎮區         0
32      龍崎區         0

In [22]:
df_pt.isna().sum()

district    0
pt_count    0
dtype: int64

In [23]:
df_pt["district"].duplicated().sum()

np.int64(0)

In [24]:
output_path = "../data/processed/pt_workforce_tainan_2024_clean.csv"

In [25]:
df_pt.to_csv(output_path, index=False, encoding="utf-8-sig")